In [1]:
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
# turn on inline if not planning to export graphs--- otherwise code gets hung up
# %matplotlib inline
import pandas as pd
import time
import os
import numpy as np
pd.options.display.max_columns = None
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MaxAbsScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import Lasso, Ridge

In [2]:
positive = pd.read_csv("PositiveData.csv", delimiter=",")
display(positive.sample(5))
display(positive.describe())

,Participant,Class,Atr1,Atr2,Atr3,Atr4,Atr5,Atr8,Atr9,Atr10,Atr11,Atr12,Atr13,Atr14,Atr15,Atr16,Atr17,Atr18,Atr19,Atr20,Atr21,Atr22,Atr23,Atr24,Atr25,Atr26,Atr27,Atr28,Atr29,Atr30
82,83,1,4,4,3,4,4,4,4,4,4,4,4,4,4,3,3,4,4,3,2,2,3,1,2,2,1,3,2,2
64,65,1,3,3,4,4,3,3,4,4,3,3,3,3,4,4,3,3,3,3,4,4,3,3,3,3,4,4,3,3
95,96,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0
113,114,0,0,2,2,1,0,0,0,2,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
109,110,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,Participant,Class,Atr1,Atr2,Atr3,Atr4,Atr5,Atr8,Atr9,Atr10,Atr11,Atr12,Atr13,Atr14,Atr15,Atr16,Atr17,Atr18,Atr19,Atr20,Atr21,Atr22,Atr23,Atr24,Atr25,Atr26,Atr27,Atr28,Atr29,Atr30
count,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000
mean,85.500000,0.494118,1.776471,1.652941,1.764706,1.482353,1.541176,1.452941,1.458824,1.576471,1.688235,1.652941,1.835294,1.570588,1.570588,1.476471,1.652941,1.517647,1.641176,1.458824,1.388235,1.247059,1.411765,1.511765,1.629412,1.488235,1.400000,1.305882,1.494118,1.494118
std,49.218899,0.501442,1.627257,1.468654,1.415444,1.504327,1.632169,1.546371,1.557976,1.421529,1.647082,1.468654,1.478421,1.502765,1.506697,1.504246,1.614512,1.565998,1.641027,1.554173,1.452149,1.446529,1.612041,1.504385,1.530079,1.500447,1.457078,1.467788,1.592315,1.504420
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,43.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,85.500000,0.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.500000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.500000,1.000000,1.000000
75%,127.750000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
max,170.000000,1.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [3]:
df = pd.DataFrame(positive)

In [4]:
df.drop(['Participant'], axis= 1)

,Class,Atr1,Atr2,Atr3,Atr4,Atr5,Atr8,Atr9,Atr10,Atr11,Atr12,Atr13,Atr14,Atr15,Atr16,Atr17,Atr18,Atr19,Atr20,Atr21,Atr22,Atr23,Atr24,Atr25,Atr26,Atr27,Atr28,Atr29,Atr30
0,1,2,2,4,1,0,0,0,0,1,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1
1,1,4,4,4,4,4,4,4,4,4,3,4,0,4,4,4,4,3,2,1,1,0,2,2,1,2,0,1,1
2,1,2,2,2,2,1,1,1,2,3,4,2,3,3,3,3,3,3,2,1,0,1,2,2,2,2,2,3,2
3,1,3,2,3,2,3,3,3,3,4,3,3,4,3,3,3,3,3,4,1,1,1,1,2,1,1,1,1,3
4,1,2,2,1,1,1,0,0,0,0,1,0,1,1,1,1,1,2,1,1,0,0,0,0,2,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
166,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
167,0,1,1,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,1,0,0,0,0,1,1,1,0,0,1
168,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
169,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,0

In [5]:
X = df[['Atr1', 'Atr2', 'Atr3', 'Atr4', 'Atr5', 'Atr8', 'Atr9', 'Atr10', 'Atr11', 'Atr12', 'Atr13', 'Atr14', 'Atr15', 'Atr16', 'Atr17', 'Atr18', 'Atr19', 'Atr20', 'Atr21', 'Atr22', 'Atr23', 'Atr24', 'Atr25', 'Atr26', 'Atr27', 'Atr28', 'Atr29', 'Atr30']]
y = df['Class'].values.reshape(-1, 1)
print(X.shape, y.shape)

(170, 28) (170, 1)

In [6]:
#  split and train that data!
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [7]:
#  use StandardScater model and fit it to the trained data
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)

In [8]:
# Transform training and testing data using scaler models
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [9]:
# Create linear Regression model and fit the data
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled, y_train_scaled)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
# plot it!
predictions = model.predict(X_test_scaled)
model.fit(X_train_scaled, y_train_scaled)
plt.scatter(model.predict(X_train_scaled), model.predict(X_train_scaled) - y_train_scaled, c="blue", label="Training Data")
plt.scatter(model.predict(X_test_scaled), model.predict(X_test_scaled) - y_test_scaled, c="orange", label="Testing Data")
plt.legend()
plt.hlines(y=0, xmin=y_test_scaled.min(), xmax=y_test_scaled.max())
plt.title("Residual Plot")
# get rid of show and close if inline is turned on
plt.show()
plt.close()

KeyboardInterrupt:

In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Fitting our model with all of our features in X
model.fit(X, y)

score = model.score(X, y)
print(f"model R2 Score: {score}")

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = model.score(X_test_scaled, y_test_scaled)


print(f"MSE: {MSE}, R2: {r2}")

model R2 Score: 0.9271510950831956
MSE: 0.16619181692184878, R2: 0.5090546704486467

In [13]:
predictions = model.predict(X)
# Plot Residuals
plt.scatter(predictions, predictions - y)
plt.hlines(y=0, xmin=predictions.min(), xmax=predictions.max())
# get rid of show and close if inline is turned on
# plt.show()
# plt.close()
print(f"True output: {y[0]}")
print(f"Predicted output: {predictions[0]}")
print(f"Prediction Error: {predictions[0]-y[0]}")

True output: [1]
Predicted output: [0.26272127]
Prediction Error: [-0.73727873]

In [14]:
print('Weight coefficients: ', model.coef_)
print('y-axis intercept: ', model.intercept_) 
model.score(X_test, y_test)

Weight coefficients:  [[-0.00226515 -0.00460378  0.03700767  0.00060787 -0.03061815 -0.04560223
   0.08204208 -0.01721496  0.05834898 -0.0483248  -0.02465294 -0.0088479
   0.0217253   0.00266974  0.10213711  0.09198069  0.02354826  0.04013593
  -0.0477155  -0.04408772  0.0093218  -0.05818321 -0.0234028   0.05456552
  -0.01181187  0.08711711  0.02226111  0.03959197]]
y-axis intercept:  [0.02057482]

0.9565758157318214

In [15]:
# LASSO
lasso = Lasso(alpha=.01).fit(X_train_scaled, y_train_scaled)

predictions = lasso.predict(X_test_scaled)

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = lasso.score(X_test_scaled, y_test_scaled)


print(f"Mean Squared Error (MSE): {MSE}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 0.11041163199477749
R-squared (R2 ): 0.8892202865713271

In [16]:
# RIDGE
ridge = Ridge(alpha=.01).fit(X_train_scaled, y_train_scaled)

predictions = ridge.predict(X_test_scaled)

MSE = mean_squared_error(y_test_scaled, predictions)
r2 = ridge.score(X_test_scaled, y_test_scaled)


print(f"Mean Squared Error (MSE): {MSE}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 0.16552716513362706
R-squared (R2 ): 0.8339210136932746

In [18]:
plt.figure(figsize=(40,40))
sns.heatmap(positive.corr(), annot=True, cmap="YlGnBu")
plt.show()

bins = np.bincount(positive["Class"].values)
plt.figure()
plt.bar(["0","1"], bins, color='black')
plt.xticks(["0","1"])
plt.xlabel('Classes')
plt.ylabel('Count')
plt.title('Histogram of Positive Attributes')
plt.savefig('Pos_histo1.png')

# get rid of close if inline is turned on, savefig does not work, only way to export is to do it without inline... its dumb
plt.close()

KeyboardInterrupt: